sudo: false
language: java
#jdk:
#  - oraclejdk8
os: osx
osx_image: xcode7.3

install:
  - '[ "${TRAVIS_OS_NAME}" = "osx" ] && brew update || true'
  - '[ "${TRAVIS_OS_NAME}" = "osx" ] && brew install ant || true'

script:
  - ant -Dnbplatform.default.harness.dir=$PWD/netbeans/harness -Dnbplatform.default.netbeans.dest.dir=$PWD/netbeans test build-mac
