image: Visual Studio 2017

#environment:
#  APPVEYOR_SAVE_CACHE_ON_ERROR: "true"

platform: x64

init:
  - cmd: choco install ant -y -f -i
  - mvn dependency:get -Dartifact=junit:junit:4.8.2 -DrepoUrl=http://repo1.maven.org/maven2/

cache:
  - C:\Users\appveyor\.m2

build_script:
  - ant -Dnbplatform.default.harness.dir=$PWD/netbeans/harness -Dnbplatform.default.netbeans.dest.dir=$PWD/netbeans -DfopCommand=fop test build-zip
 

# Tests

#test_script:
#  - ant test 

artifacts:
  - path: dist\blue*.zip
    name: Blue Zip 
    type: zip

#cache:
# - C:\Tools\vcpkg\ -> C:\projects\csound\msvc\downloadDependencies.ps1
# - C:\projects\csound\msvc\cache

#notifications:
#  - provider: Email
#    to:
#      - CSOUND-DEV@listserv.heanet.ie
#    subject: 'Build {{status}}'     # optional
#    on_build_success: false
#    on_build_failure: true
#    on_build_status_changed: false
